trigger:
- dev

pool:
  name: 'azureagent'

steps:

# Step 1: Scan the ZIP File with Veracode
- task: CmdLine@2
  displayName: Veracode SCA Scan
  inputs:
    script: |
      curl -sSL https://sca-downloads.veracode.com/ci.sh | sh -s -- scan --allow-dirty --no-upload